# Prioritized targets:
# - Do a CI build on push without errors
# - Do a Deployment to AWS on push to the production branch
# - Test creating / editing a story ?
# - Test creating a user and seeing if the example story is set up correctly ?

# https://github.com/marketplace/actions/amplify-cli-action

name: 'Build (and test)'
on: [push]

jobs:
  build:
    name: build TerriaMap and terriajs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x,latest]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install
        
      - name: Build with gulp
        run: npx gulp release
      
        
