# Prioritized targets:
# - Do a CI build on push without errors
# - Do a Deployment to AWS on push to the production branch
# - Test creating / editing a story ?
# - Test creating a user and seeing if the example story is set up correctly ?

# https://github.com/marketplace/actions/amplify-cli-action

name: 'Build (and test)'
on: [push]

jobs:
  build:
    name: build TerriaMap and terriajs
    runs-on: ubuntu-latest

    env:
      TERRIA_MAP_DIR: /home/runner/work/TerriaMap
      TERRIA_JS_DIR: /home/runner/work/TerriaMap/TerriaMap/packages/terriajs

    strategy:
      fail-fast: false
      matrix:
        node-version: ['14.x','16.x']

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn install
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline # Prefer-offline checks the cache

      - name: Install amplify with npm
        run: npm install -g @aws-amplify/cli

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: dev
          project_dir: packages/terriajs/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Chown amplify directory
        run: |
          sudo chown -R runner:docker ${{ env.TERRIA_JS_DIR }}/amplify
          ls -l ${{ env.TERRIA_JS_DIR }}/amplify/.config/

      - name: Checkout the exports file from the amplify environment
        run: |
          cd packages/terriajs
          amplify pull

      - name: move aws-exports.js to the correct location
        run: mv aws-exports.js lib/aws-exports.js
        working-directory: packages/terriajs

      - name: Build with gulp
        run: npx gulp release


