# Prioritized targets:
# - Do a CI build on push without errors
# - Do a Deployment to AWS on push to the production branch
# - Test creating / editing a story ?
# - Test creating a user and seeing if the example story is set up correctly ?

# https://github.com/marketplace/actions/amplify-cli-action

name: 'Build (and test)'
on: [push]

jobs:
  build:
    name: build TerriaMap and terriajs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x','16.x']

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: prod
          project_dir: packages/terriajs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: move aws-exports.js to the correct location
        run: mv aws-exports.js lib/aws-exports.js
        working-directory: packages/terriajs
        
      - name: Build with gulp
        run: npx gulp release
      
        
